### ISSUE TITLE
bug: I am getting eslint error for import of masonry wall

### ISSUE THREAD

**Issue by iCreatorStudio** [DerYeger/yeger#238]
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

I'm getting below eslint error.

```
Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ****\vue-laravel\javascript\full-version\node_modules\@yeger\vue-masonry-wall\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:572:36)
    at Module._findPath (node:internal/modules/cjs/loader:641:31)
    at findModulePath (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:99:27)
    at exports.resolve (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:75:10)
    at withResolver (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:114:23)
    at fullResolve (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:135:22)
    at relative (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:84:10)eslint[import/namespace](https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/namespace.md)
Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ***\vue-laravel\javascript\full-version\node_modules\@yeger\vue-masonry-wall\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:572:36)
    at Module._findPath (node:internal/modules/cjs/loader:641:31)
    at findModulePath (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:99:27)
    at exports.resolve (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:75:10)
    at withResolver (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:114:23)
    at fullResolve (****\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:135:22)
    at relative (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:84:10)eslint[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/no-unresolved.md)
Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ***\vue-laravel\javascript\full-version\node_modules\@yeger\vue-masonry-wall\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:572:36)
    at Module._findPath (node:internal/modules/cjs/loader:641:31)
    at findModulePath (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:99:27)
    at exports.resolve (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:75:10)
    at withResolver (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:114:23)
    at fullResolve (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:135:22)
    at relative (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:84:10)eslint[import/default](https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/default.md)
Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ***\vue-laravel\javascript\full-version\node_modules\@yeger\vue-masonry-wall\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:572:36)
    at Module._findPath (node:internal/modules/cjs/loader:641:31)
    at findModulePath (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:99:27)
    at exports.resolve (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:75:10)
    at withResolver (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:114:23)
    at fullResolve (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:135:22)
    at relative (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:84:10)eslint[import/no-duplicates](https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/no-duplicates.md)
Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ***\vue-laravel\javascript\full-version\node_modules\@yeger\vue-masonry-wall\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:572:36)
    at Module._findPath (node:internal/modules/cjs/loader:641:31)
    at findModulePath (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:99:27)
    at exports.resolve (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:75:10)
    at withResolver (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:114:23)
    at fullResolve (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:135:22)
    at relative (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:84:10)eslint[import/no-named-as-default](https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/no-named-as-default.md)
Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in ***\vue-laravel\javascript\full-version\node_modules\@yeger\vue-masonry-wall\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:572:36)
    at Module._findPath (node:internal/modules/cjs/loader:641:31)
    at findModulePath (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:99:27)
    at exports.resolve (***\vue-laravel\javascript\full-version\node_modules\eslint-import-resolver-alias\index.js:75:10)
    at withResolver (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:114:23)
    at fullResolve (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:135:22)
    at relative (***\vue-laravel\javascript\full-version\node_modules\eslint-module-utils\resolve.js:84:10)eslint[import/no-named-as-default-member](https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/no-named-as-default-member.md)
```

### Reproduction

Just import the plugin

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
The exports of this package are well defined. Please open an issue for the eslint plugin instead.
